---
- name: "Build a Cloud Big Data cluster"
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: "Cloud Big Data cluster create request"
      local_action:
        module: rax_cbd
        credentials: "{{ rax_credentials_file }}"
        name: "{{ cluster_name }}"
        type: "{{ cluster_type }}"
        flavor: "{{ cluster_flavor }}"
        nodes: "{{ cbd_nodes }}"
        profile_username: "{{ profile_username }}"
        profile_password: "{{ profile_password }}"
        postinit_script: "{{ postinit_script }}"
        sshkeyname: "{{ ssh.keyname }}"
        sshkeyfile: "{{ ssh.keyfile }}"
        region: "{{ rax_region }}"
        state: present
        wait: true
        wait_timeout: 40
      register: my_cbd

    - debug: var=my_cbd

    - name: "Add gateway to group"
      local_action:
        module: add_host
        hostname: "{{ my_cbd.cluster.gateway.name }}"
        ansible_ssh_host: "{{ my_cbd.cluster.gateway.public_v4_address }}"
        ansible_ssh_user: "{{ my_cbd.cluster.credentials.profile_username }}"
        groupname: gateway
      when: my_cbd.cluster.status == 'ACTIVE'

    - name: "Add namenode to group"
      local_action:
        module: add_host
        hostname: "{{ my_cbd.cluster.namenode.name }}"
        ansible_ssh_host: "{{ my_cbd.cluster.namenode.public_v4_address }}"
        ansible_ssh_user: "{{ my_cbd.cluster.credentials.profile_username }}"
        groupname: nodes
      when: my_cbd.cluster.status == 'ACTIVE'

    - name: "Add datanodes to group"
      local_action:
        module: add_host
        hostname: "{{ item.name }}"
        ansible_ssh_host: "{{ item.public_v4_address }}"
        ansible_ssh_user: "{{ my_cbd.cluster.credentials.profile_username }}"
        groupname: nodes
      with_items: my_cbd.cluster.datanodes
      when: my_cbd.cluster.status == 'ACTIVE'


- name: "Configure gateway"
  hosts: gateway
  sudo: yes
  tasks:
    - name: "Install sysstat"
      yum: name=sysstat state=latest


- name: "Configure nodes"
  hosts: nodes
  sudo: yes
  tasks:
    - name: "Install sysstat"
      yum: name=sysstat state=latest


- name: "Upload the test file to Cloud Files"
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: "Download the file first"
      get_url:
        url: "{{ local_input.file_url }}"
        dest: /tmp/{{ cloud_files.file_name }}
        validate_certs: no

    - name: "Create the container"
      rax_files:
        container: "{{ cloud_files.container }}"
        region: "{{ rax_region }}"
        credentials: "{{ rax_credentials_file }}"

    - name: "Upload the file to the Cloud Files container"
      rax_files_objects:
        container: "{{ cloud_files.container }}"
        region: "{{ rax_region }}"
        method: put
        src: /tmp/{{ cloud_files.file_name }}
        credentials: "{{ rax_credentials_file }}"


- name: "Run MR job"
  hosts: gateway
  tasks:
    - command: hadoop jar /usr/lib/hadoop-mapreduce/hadoop-mapreduce-examples.jar wordcount swift://{{ cloud_files.container }}.rack-{{ rax_region|lower }}/{{ cloud_files.file_name }} swift://{{ cloud_files.container }}.rack-{{ rax_region|lower }}/{{ cloud_files.output_folder }}
      when: cluster_type != "HADOOP_HDP2_2"
    - command: hadoop jar /usr/hdp/current/hadoop-mapreduce-client/hadoop-mapreduce-examples.jar wordcount swift://{{ cloud_files.container }}.rack-{{ rax_region|lower }}/{{ cloud_files.file_name }} swift://{{ cloud_files.container }}.rack-{{ rax_region|lower }}/{{ cloud_files.output_folder }}
      when: cluster_type == "HADOOP_HDP2_2"


- name: "Download result file from cloud files"
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: "Download one file from test container"
      rax_files_objects:
        container: "{{ cloud_files.container }}"
        region: "{{ rax_region }}"
        src: "{{ cloud_files.output_folder }}/part-r-00000"
        credentials: "{{ rax_credentials_file }}"
        dest: "{{ local_output.folder }}"


- name: "Delete environment"
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: "Delete test cluster"
      local_action:
        module: rax_cbd
        credentials: "{{ rax_credentials_file }}"
        name: "{{ cluster_name }}"
        region: "{{ rax_region }}"
        state: absent
        wait: true

